command: ['python', 'app.py']
env:
  - name: 'HOME'
    value: '/app/python/source_code'
  - name: 'SHELL'
    value: '/usr/bin/bash'
  - name: 'DATABRICKS_APP_DEPLOYMENT'
    value: 'true'
  - name: 'UV_PYTHON'
    value: '/usr/bin/python3.11'